-- AUTO-GENERATED by `python3 tools/tts_bridge.py sync-mock`.
-- Не редактировать руками — правьте data/characters/*.json и запустите
-- sync-mock заново (или push --sync-mock). Ниже — не Lua-копия,
-- а сырой JSON из тех файлов, склеенный в массив 1:1.
return JSON.decode([==[
[
{
  "id": "char_kellen",
  "name": "Кэллен",
  "portrait": "",
  "playerName": "Антон",
  "race": "Human",
  "class": "Fighter",
  "level": 3,
  "background": "Солдат",
  "alignment": "Законно-добрый",
  "experience": { "current": 900, "next": 2700 },
  "hp": { "current": 24, "max": 28, "temp": 0 },
  "speed": 30,
  "hitDice": "3d10",
  "deathSaves": { "successes": 0, "failures": 0 },
  "abilityScores": {
    "STR": 16,
    "DEX": 12,
    "CON": 14,
    "INT": 10,
    "WIS": 11,
    "CHA": 13
  },
  "proficiencyBonus": 2,
  "inspiration": false,
  "savingThrowProficiencies": ["STR", "CON"],
  "proficientSkills": ["athletics", "intimidation", "perception"],
  "combat": { "armorClass": 17, "meleeBonus": 5, "rangedBonus": 2 },
  "attacks": [
    { "name": "Длинный меч", "atkBonus": "+5", "damage": "1d8+3 рубящий" },
    { "name": "Короткий лук", "atkBonus": "+3", "damage": "1d6+1 колющий" }
  ],
  "carryWeight": { "current": 84, "max": 180 },
  "attunement": { "used": 0, "max": 3 },
  "equipment": [
    { "slot": "armor", "itemId": "leather_armor", "name": "Кожаный доспех" },
    { "slot": "accessory1", "itemId": null, "name": null },
    { "slot": "accessory2", "itemId": null, "name": null },
    { "slot": "hand_r", "itemId": null, "name": "Длинный меч" },
    { "slot": "hand_l", "itemId": null, "name": null }
  ],
  "inventory": [
    { "itemId": "potion_healing", "name": "Зелье лечения", "qty": 2 },
    { "itemId": "torch", "name": "Факел", "qty": 3 }
  ],
  "abilities": [
    { "id": "power_attack", "name": "Мощный удар", "actionType": "action" },
    { "id": "second_wind", "name": "Второе дыхание", "actionType": "bonus_action" },
    { "id": "opportunity_attack", "name": "Атака возможности", "actionType": "reaction" }
  ],
  "spellSlots": [],
  "personality": {
    "traits": "Всегда прикрывает спину товарищам.",
    "ideals": "Долг превыше всего.",
    "bonds": "Поклялся защищать деревню, где вырос.",
    "flaws": "Слишком доверяет старшим по званию."
  },
  "otherProficiencies": [
    "Языки: Общий",
    "Владение: лёгкие и средние доспехи, щиты, простое и воинское оружие"
  ],
  "notes": ""
},
{
  "id": "char_mira",
  "name": "Мира",
  "portrait": "",
  "playerName": "Анна",
  "race": "Elf",
  "class": "Wizard",
  "level": 3,
  "background": "Отшельница",
  "alignment": "Нейтрально-добрый",
  "experience": { "current": 900, "next": 2700 },
  "hp": { "current": 16, "max": 18, "temp": 0 },
  "speed": 30,
  "hitDice": "3d6",
  "deathSaves": { "successes": 0, "failures": 0 },
  "abilityScores": {
    "STR": 8,
    "DEX": 14,
    "CON": 12,
    "INT": 17,
    "WIS": 13,
    "CHA": 10
  },
  "proficiencyBonus": 2,
  "inspiration": true,
  "savingThrowProficiencies": ["INT", "WIS"],
  "proficientSkills": ["arcana", "investigation", "insight"],
  "combat": { "armorClass": 12, "meleeBonus": 1, "rangedBonus": 5 },
  "attacks": [
    { "name": "Посох", "atkBonus": "+1", "damage": "1d6-1 дробящий" },
    { "name": "Огненный снаряд", "atkBonus": "+5", "damage": "2d10 огонь" }
  ],
  "carryWeight": { "current": 32, "max": 90 },
  "attunement": { "used": 1, "max": 3 },
  "equipment": [
    { "slot": "armor", "itemId": null, "name": null },
    { "slot": "accessory1", "itemId": "amulet_arcana", "name": "Амулет тайной силы" },
    { "slot": "accessory2", "itemId": null, "name": null },
    { "slot": "hand_r", "itemId": null, "name": "Посох" },
    { "slot": "hand_l", "itemId": null, "name": null }
  ],
  "inventory": [
    { "itemId": "potion_healing", "name": "Зелье лечения", "qty": 1 }
  ],
  "abilities": [
    { "id": "firebolt", "name": "Огненный снаряд", "actionType": "action", "usesSpellSlot": false, "spellLevel": 0 },
    { "id": "shield_spell", "name": "Щит (заклинание)", "actionType": "reaction", "usesSpellSlot": true, "spellLevel": 1 }
  ],
  "spellSlots": [
    { "level": 1, "max": 4, "used": 2 },
    { "level": 2, "max": 3, "used": 2 }
  ],
  "personality": {
    "traits": "Записывает каждую находку в дневник.",
    "ideals": "Знание должно быть свободным.",
    "bonds": "Ищет утраченный гримуар наставницы.",
    "flaws": "Не может пройти мимо неразгаданной тайны."
  },
  "otherProficiencies": [
    "Языки: Общий, Эльфийский, Драконий",
    "Владение: посохи, кинжалы, воровские инструменты"
  ],
  "notes": ""
}
]
]==])
