-- AUTO-GENERATED by `python3 tools/tts_bridge.py sync-mock`.
-- Не редактировать руками — правьте data/characters/*.json и запустите
-- sync-mock заново (или push, он делает это сам). Ниже — не Lua-копия,
-- а сырой JSON из тех файлов, склеенный в массив 1:1.
return JSON.decode([==[
[
{
  "id": "char_kellen",
  "name": "Кэллен",
  "portrait": "",
  "race": "Human",
  "class": "Fighter",
  "level": 3,
  "hp": { "current": 24, "max": 28 },
  "abilityScores": {
    "STR": 16,
    "DEX": 12,
    "CON": 14,
    "INT": 10,
    "WIS": 11,
    "CHA": 13
  },
  "equipment": [
    { "slot": "mainHand", "itemId": "longsword", "name": "Длинный меч" },
    { "slot": "offHand", "itemId": "shield", "name": "Щит" },
    { "slot": "armor", "itemId": "leather_armor", "name": "Кожаный доспех" },
    { "slot": "head", "itemId": null, "name": null },
    { "slot": "boots", "itemId": null, "name": null },
    { "slot": "accessory", "itemId": null, "name": null }
  ],
  "inventory": [
    { "itemId": "potion_healing", "name": "Зелье лечения", "qty": 2 },
    { "itemId": "torch", "name": "Факел", "qty": 3 }
  ],
  "abilities": [
    { "id": "power_attack", "name": "Мощный удар" },
    { "id": "second_wind", "name": "Второе дыхание" }
  ],
  "hotbar": ["power_attack", "second_wind"],
  "notes": ""
},
{
  "id": "char_mira",
  "name": "Мира",
  "portrait": "",
  "race": "Elf",
  "class": "Wizard",
  "level": 3,
  "hp": { "current": 16, "max": 18 },
  "abilityScores": {
    "STR": 8,
    "DEX": 10,
    "CON": 12,
    "INT": 17,
    "WIS": 13,
    "CHA": 10
  },
  "equipment": [
    { "slot": "mainHand", "itemId": "quarterstaff", "name": "Посох" },
    { "slot": "offHand", "itemId": null, "name": null },
    { "slot": "armor", "itemId": null, "name": null },
    { "slot": "head", "itemId": null, "name": null },
    { "slot": "boots", "itemId": null, "name": null },
    { "slot": "accessory", "itemId": "amulet_arcana", "name": "Амулет тайной силы" }
  ],
  "inventory": [
    { "itemId": "potion_healing", "name": "Зелье лечения", "qty": 1 }
  ],
  "abilities": [
    { "id": "firebolt", "name": "Огненный снаряд" },
    { "id": "shield_spell", "name": "Щит (заклинание)" }
  ],
  "hotbar": ["firebolt", "shield_spell"],
  "notes": ""
}
]
]==])
