#!/usr/bin/env python3
"""External Editor API bridge for Tabletop Simulator.

Protocol: https://api.tabletopsimulator.com/externaleditorapi/
- We send messages to TTS on 127.0.0.1:39999 (one JSON object per connection).
- TTS sends messages to us on 127.0.0.1:39998 (one JSON object per connection,
  terminated by TTS closing the socket).

Commands:
    pull    fetch all scripts/UI from the running game into .tts/objects/
    push    send everything in .tts/objects/ back to the game (Save & Play)
    watch   print live debug/error messages from the running game
"""
import argparse
import json
import re
import socket
import sys
import threading
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Same layout the VS Code extension (sebaestschjin.tts-editor) uses, so the
# hotkeys (Ctrl+Alt+L / Ctrl+Alt+S) and this script operate on the same files.
TTS_DIR = ROOT / ".tts"
OBJECTS = TTS_DIR / "objects"
MANIFEST = TTS_DIR / "manifest.json"
SRC = ROOT / "src"
DATA = ROOT / "data"
MOCK_DATA_PATH = SRC / "core" / "MockData.lua"

REQUIRE_RE = re.compile(r'require\(\s*[\'"]([\w.]+)[\'"]\s*\)')


def sync_mock_data(_args=None) -> None:
    """Regenerate src/data/MockData.lua from data/characters/*.json.

    This does NOT re-encode JSON into a Lua table literal — it glues the raw
    file contents into a JSON array and wraps that verbatim text in
    JSON.decode([==[ ... ]==]). The generated file is therefore just your
    JSON, byte-for-byte, plus two lines of Lua — never a hand-authored-looking
    duplicate. TTS's Lua sandbox can't read files from disk at runtime, so
    *some* .lua wrapper has to exist for require() to find; this keeps it as
    thin as that constraint allows. Hand edits to MockData.lua get clobbered
    on the next sync, by design (CLAUDE.md rule 2: JSON is the source of
    truth, scripts only load it)."""
    characters_dir = DATA / "characters"
    files = sorted(characters_dir.glob("*.json"))
    if not files:
        print(f"No character JSON files found in {characters_dir}", file=sys.stderr)
        sys.exit(1)

    raw_parts = []
    for f in files:
        text = f.read_text(encoding="utf-8")
        json.loads(text)  # validate only — fail fast on typos, don't reformat
        raw_parts.append(text.strip())
    merged = "[\n" + ",\n".join(raw_parts) + "\n]\n"

    if "]==]" in merged:
        raise ValueError(
            "a character JSON file contains ']==]', which breaks the Lua "
            "long-string wrapper — rename/escape that content"
        )

    output = (
        "-- AUTO-GENERATED by `python3 tools/tts_bridge.py sync-mock`.\n"
        "-- Не редактировать руками — правьте data/characters/*.json и запустите\n"
        "-- sync-mock заново (или push --sync-mock). Ниже — не Lua-копия,\n"
        "-- а сырой JSON из тех файлов, склеенный в массив 1:1.\n"
        "return JSON.decode([==[\n"
        f"{merged}"
        "]==])\n"
    )
    MOCK_DATA_PATH.write_text(output, encoding="utf-8")
    print(f"Wrote {MOCK_DATA_PATH.relative_to(ROOT)} from {len(files)} file(s): "
          f"{', '.join(f.name for f in files)}")


AUTOGEN_MARKER = "-- AUTO-GENERATED from "
COMMENT_RE = re.compile(r"<!--.*?-->\s*", re.S)
LAYOUT_DIR = "layout"      # .xml-исходники, которые правит человек
GENERATED_DIR = "generated"  # .lua-обёртки, которые пишет этот скрипт


LAYOUT_GROUPS = ("VerticalLayout", "HorizontalLayout", "GridLayout", "TableLayout")
# Сырые layout-группы разрешены только в разметке самих раскладочных
# компонентов: там ровно две проверенные в TTS конфигурации — «fluid» (только
# padding/spacing/childAlignment) и «fixed» (плюс все четыре child*-флага
# false). Любая третья комбинация ломает вёрстку: childControlWidth по
# умолчанию true, и группа переопределяет width/height детей.
LAYOUT_COMPONENTS = {"Stack", "StackFixed", "Line", "LineFixed", "Column", "ColumnFixed", "Anchor"}
RAW_GROUP_RE = re.compile(r"<(" + "|".join(("VerticalLayout", "HorizontalLayout")) + r")\b")
SIZED_GROUP_RE = re.compile(
    r"<(" + "|".join(LAYOUT_GROUPS) + r")\b[^>]*\b(width|height|color)\s*=",
    re.S,
)


def lint_layout(path: Path, markup: str) -> int:
    """Ругается на размер/цвет, повешенный прямо на layout-группу.

    Из документации TTS (api.tabletopsimulator.com/ui/layoutgrouping) у групп
    есть только padding/spacing/childAlignment: color рисуется ПОВЕРХ детей, а
    width на <VerticalLayout> — то, из-за чего лист персонажа развалился.
    Размер и фон живут на Panel (компоненты Box/Column/Section)."""
    problems = 0

    if path.stem not in LAYOUT_COMPONENTS:
        for match in RAW_GROUP_RE.finditer(markup):
            line = markup[: match.start()].count("\n") + 1
            print(
                f"  ERROR: {path.relative_to(ROOT)}:{line} — сырой <{match.group(1)}>: "
                "используйте <Stack>/<Line>/<Column> (fit=\"fixed\" для детей со своим размером)",
                file=sys.stderr,
            )
            problems += 1

    for match in SIZED_GROUP_RE.finditer(markup):
        line = markup[: match.start()].count("\n") + 1
        print(
            f"  ERROR: {path.relative_to(ROOT)}:{line} — <{match.group(1)} {match.group(2)}=...>: "
            "размер и фон только на Panel (Box/Column/Section)",
            file=sys.stderr,
        )
        problems += 1
    return problems


def sync_xml_templates(_args=None) -> int:
    """Собирает всю разметку из ui/layout/**/*.xml в ОДИН модуль ui/generated/Templates.lua.

    Почему один файл, а не обёртка на каждый .xml: обёрток было по файлу на
    компонент, и они оказывались тёзками контрактов (components/Box.lua и
    components/generated/Box.lua) — в дереве это читалось как дубликаты.
    Теперь генерируемый артефакт ровно один, и его имя ни с чем не пересекается.

    Зачем он вообще нужен: песочница TTS не читает файлы в рантайме, скрипт
    объекта в сейве — одна плоская строка, а бандлер расширения резолвит только
    src/?.lua — то есть текст XML обязан лежать внутри отправляемого Lua.

    Возвращает 1, если файл изменился, чтобы watch-xml молчал впустую."""
    changed, problems = 0, 0

    layout_roots = sorted([x for x in SRC.rglob(LAYOUT_DIR) if x.is_dir()])
    if not layout_roots:
        return changed

    def under_layout_root(path: Path) -> bool:
        for root in layout_roots:
            try:
                path.relative_to(root)
                return True
            except ValueError:
                pass
        return False

    strays = [x for x in sorted(SRC.rglob("*.xml")) if not under_layout_root(x)]
    for stray in strays:
        print(
            f"  WARNING: {stray.relative_to(ROOT)} лежит вне {LAYOUT_DIR}/** — "
            "в Templates.lua он не попадёт",
            file=sys.stderr,
        )

    for layout_root in layout_roots:
        target = layout_root.parent / GENERATED_DIR / "Templates.lua"
        target.parent.mkdir(parents=True, exist_ok=True)

        xml_files = sorted(layout_root.rglob("*.xml"))
        entries = []
        seen_names = {}
        for xml in xml_files:
            # Комментарии — документация для того, кто правит разметку; в игру
            # их гнать незачем: строка XML парсится заново на каждый setXml, а
            # шапка атома вроде InputField.xml размножилась бы по инстансам.
            markup = COMMENT_RE.sub("", xml.read_text(encoding="utf-8")).strip()
            problems += lint_layout(xml, markup)
            if xml.stem in seen_names:
                print(
                    f"  ERROR: дублируется имя шаблона {xml.stem}: "
                    f"{seen_names[xml.stem].relative_to(ROOT)} и {xml.relative_to(ROOT)}",
                    file=sys.stderr,
                )
                problems += 1
                continue
            seen_names[xml.stem] = xml
            entries.append((xml.stem, markup))

        body = [
            f"-- AUTO-GENERATED из {layout_root.relative_to(ROOT)}/**/*.xml "
            "командой `python3 tools/tts_bridge.py sync-xml`.",
            "-- Не редактировать руками — правьте .xml, файл пересобирается.",
            "-- Внутри — та же разметка без XML-комментариев.",
            "local Templates = {}",
            "",
        ]
        for name, markup in entries:
            body.append(f'Templates["{name}"] = {lua_long_string(markup)}')
            body.append("")
        body.append("return Templates")
        output = "\n".join(body) + "\n"

        if not target.exists() or target.read_text(encoding="utf-8") != output:
            target.write_text(output, encoding="utf-8")
            print(f"  {len(entries)} шаблон(ов) -> {target.relative_to(ROOT)}")
            changed = 1

    if problems:
        print(f"  {problems} проблем(ы) в разметке — см. ERROR выше", file=sys.stderr)
    return changed


def watch_xml(_args=None) -> None:
    """Poll src/**/*.xml and keep the generated .lua wrappers in sync.

    Touches no sockets, so it is safe to run alongside the VS Code extension
    (unlike `watch`/`push`, which fight it for port 39998)."""
    print("Watching src/**/*.xml -> .lua wrappers (Ctrl+C to stop)...")
    sync_xml_templates()
    try:
        while True:
            time.sleep(0.5)
            sync_xml_templates()
    except KeyboardInterrupt:
        pass


def resolve_module_file(name: str) -> Path:
    base = SRC / name.replace(".", "/")
    lua_path = base.with_suffix(".lua")
    if lua_path.exists():
        return lua_path

    xml_path = base.with_suffix(".xml")
    if xml_path.exists():
        return xml_path

    return lua_path


def lua_long_string(text: str) -> str:
    level = 0
    while True:
        opening = "[" + ("=" * level) + "["
        closing = "]" + ("=" * level) + "]"
        if closing not in text:
            return f"{opening}{text}{closing}"
        level += 1


def bundle_lua(entry_source: str) -> str:
    """Statically inline require()'d modules, mirroring what the TTS Editor
    VS Code extension does on Save and Play. TTS's Lua sandbox has no real
    package/require system, so every require() call site gets served at
    runtime by a tiny shim defined in a prelude, with each module's source
    wrapped as a lazily-invoked closure."""
    discovered = {}
    queue = list(REQUIRE_RE.findall(entry_source))
    while queue:
        name = queue.pop()
        if name in discovered:
            continue
        path = resolve_module_file(name)
        if not path.exists():
            raise FileNotFoundError(f'require("{name}") -> {path} not found')
        source = path.read_text(encoding="utf-8")
        if path.suffix == ".xml":
            discovered[name] = "return " + lua_long_string(source)
            continue

        discovered[name] = source
        queue.extend(REQUIRE_RE.findall(source))

    if not discovered:
        return entry_source

    prelude = [
        "local __tts_modules, __tts_cache = {}, {}",
        "local function require(name)",
        "  if __tts_cache[name] ~= nil then return __tts_cache[name] end",
        "  local fn = __tts_modules[name]",
        "  if fn == nil then error('module not found: ' .. tostring(name)) end",
        "  local result = fn()",
        "  __tts_cache[name] = result",
        "  return result",
        "end",
    ]
    for name, source in discovered.items():
        prelude.append(f'__tts_modules["{name}"] = function()')
        prelude.append(source)
        prelude.append("end")

    return "\n".join(prelude) + "\n\n" + entry_source

SEND_PORT = 39999
RECV_PORT = 39998
HOST = "127.0.0.1"


def send_message(payload: dict) -> None:
    with socket.create_connection((HOST, SEND_PORT), timeout=5) as s:
        s.sendall(json.dumps(payload).encode("utf-8"))


def wait_for_message(expected_id: int, timeout: float = 15.0) -> dict:
    """Start a one-shot listener on RECV_PORT and return the first message
    matching expected_id (mirrors how TTS's own external editor works: it
    opens a fresh connection per outgoing message and closes it when done)."""
    result = {}
    done = threading.Event()

    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srv.bind((HOST, RECV_PORT))
    srv.listen(5)
    srv.settimeout(timeout)

    def accept_loop():
        end_time = time.time() + timeout
        while time.time() < end_time and not done.is_set():
            try:
                srv.settimeout(max(0.1, end_time - time.time()))
                conn, _ = srv.accept()
            except socket.timeout:
                break
            chunks = []
            conn.settimeout(5)
            try:
                while True:
                    data = conn.recv(65536)
                    if not data:
                        break
                    chunks.append(data)
            except socket.timeout:
                pass
            conn.close()
            if not chunks:
                continue
            try:
                msg = json.loads(b"".join(chunks).decode("utf-8"))
            except json.JSONDecodeError:
                continue
            if msg.get("messageID") == expected_id:
                result["msg"] = msg
                done.set()
                break

    t = threading.Thread(target=accept_loop, daemon=True)
    t.start()
    t.join(timeout + 1)
    srv.close()
    if "msg" not in result:
        raise TimeoutError(
            f"Timed out waiting for messageID={expected_id} from TTS. "
            "Is Tabletop Simulator running with a save loaded?"
        )
    return result["msg"]


def safe_filename(name: str, guid: str) -> str:
    """Mirror tts-editor's naming: object name minus path-hostile chars, then guid."""
    name = re.sub(r'[":<>/\\|?*\r\n]', "", (name or "Object")).strip() or "Object"
    return f"{name}.{guid}"


def pull(_args) -> None:
    OBJECTS.mkdir(parents=True, exist_ok=True)

    print("Requesting scripts from TTS...")
    send_message({"messageID": 0})
    msg = wait_for_message(expected_id=1)
    states = msg.get("scriptStates", [])
    print(f"Received {len(states)} script state(s).")

    manifest = []
    for st in states:
        guid = st["guid"]
        name = st.get("name", "Object")
        script = st.get("script", "") or ""
        ui = st.get("ui", "") or ""

        if guid == "-1":
            lua_path = OBJECTS / "Global.lua"
            xml_path = OBJECTS / "Global.xml"
        else:
            base = safe_filename(name, guid)
            lua_path = OBJECTS / f"{base}.lua"
            xml_path = OBJECTS / f"{base}.xml"

        lua_path.write_text(script, encoding="utf-8")
        xml_path.write_text(ui, encoding="utf-8")

        manifest.append(
            {
                "guid": guid,
                "name": name,
                "lua": str(lua_path.relative_to(ROOT)),
                "xml": str(xml_path.relative_to(ROOT)),
            }
        )

    MANIFEST.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {len(manifest)} object(s) to {OBJECTS.relative_to(ROOT)}/")


def push(args) -> None:
    if not MANIFEST.exists():
        print("No .tts/manifest.json found — run `pull` first.", file=sys.stderr)
        sys.exit(1)

    if args.sync_mock:
        sync_mock_data()
    sync_xml_templates()

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    script_states = []
    for entry in manifest:
        lua_path = ROOT / entry["lua"]
        xml_path = ROOT / entry["xml"]
        script = lua_path.read_text(encoding="utf-8") if lua_path.exists() else ""
        script = bundle_lua(script)
        ui = xml_path.read_text(encoding="utf-8") if xml_path.exists() else ""
        script_states.append(
            {"guid": entry["guid"], "script": script, "ui": ui}
        )

    print(f"Pushing {len(script_states)} object(s) to TTS (Save & Play)...")
    send_message({"messageID": 1, "scriptStates": script_states})
    try:
        wait_for_message(expected_id=1, timeout=20)
        print("TTS reloaded successfully.")
    except TimeoutError:
        print("Sent, but did not see a reload confirmation in time.", file=sys.stderr)
    except OSError as e:
        print(f"Sent (couldn't listen for confirmation: {e}).", file=sys.stderr)
        print("Port 39998 is likely held by the VS Code extension — check its output/console, or TTS directly, to confirm the reload.", file=sys.stderr)


def watch(_args) -> None:
    print(f"Listening on {HOST}:{RECV_PORT} for TTS console output (Ctrl+C to stop)...")
    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srv.bind((HOST, RECV_PORT))
    srv.listen(5)
    try:
        while True:
            conn, _ = srv.accept()
            chunks = []
            while True:
                data = conn.recv(65536)
                if not data:
                    break
                chunks.append(data)
            conn.close()
            if not chunks:
                continue
            try:
                msg = json.loads(b"".join(chunks).decode("utf-8"))
            except json.JSONDecodeError:
                continue
            mid = msg.get("messageID")
            if mid == 2:
                print(f"[print] {msg.get('message')}")
            elif mid == 3:
                print(f"[error] {msg.get('errorMessagePrefix', '')}{msg.get('error')}")
            elif mid == 6:
                print("[saved]")
            elif mid == 7:
                print(f"[object created] guid={msg.get('guid')}")
            elif mid == 0:
                print(f"[scripting editor opened for new object] {msg.get('scriptStates')}")
            else:
                print(f"[msg {mid}] {msg}")
    except KeyboardInterrupt:
        pass
    finally:
        srv.close()


def main():
    parser = argparse.ArgumentParser(description="TTS External Editor API bridge")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("pull", help="fetch scripts/UI from the running game into src/")
    push_parser = sub.add_parser("push", help="send src/ back to the running game (Save & Play)")
    push_parser.add_argument(
        "--sync-mock",
        action="store_true",
        help="regenerate src/core/MockData.lua from data/characters/*.json before push",
    )
    sub.add_parser("watch", help="print live print()/error messages from the game")
    sub.add_parser("sync-mock", help="regenerate src/data/MockData.lua from data/characters/*.json")
    sub.add_parser("sync-xml", help="rebuild ui/generated/Templates.lua from ui/layout/**/*.xml")
    sub.add_parser("watch-xml", help="keep Templates.lua in sync while you edit layout/**/*.xml")

    args = parser.parse_args()
    {
        "pull": pull,
        "push": push,
        "watch": watch,
        "sync-mock": sync_mock_data,
        "sync-xml": sync_xml_templates,
        "watch-xml": watch_xml,
    }[args.command](args)


if __name__ == "__main__":
    main()
