#!/usr/bin/env python3
"""External Editor API bridge for Tabletop Simulator.

Protocol: https://api.tabletopsimulator.com/externaleditorapi/
- We send messages to TTS on 127.0.0.1:39999 (one JSON object per connection).
- TTS sends messages to us on 127.0.0.1:39998 (one JSON object per connection,
  terminated by TTS closing the socket).

Commands:
    pull    fetch all scripts/UI from the running game into .tts/objects/
    push    send everything in .tts/objects/ back to the game (Save & Play)
    watch   print live debug/error messages from the running game
"""
import argparse
import json
import re
import socket
import sys
import threading
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Same layout the VS Code extension (sebaestschjin.tts-editor) uses, so the
# hotkeys (Ctrl+Alt+L / Ctrl+Alt+S) and this script operate on the same files.
TTS_DIR = ROOT / ".tts"
OBJECTS = TTS_DIR / "objects"
MANIFEST = TTS_DIR / "manifest.json"
SRC = ROOT / "src"
DATA = ROOT / "data"
MOCK_DATA_PATH = SRC / "core" / "MockData.lua"

REQUIRE_RE = re.compile(r'require\(\s*[\'"]([\w.]+)[\'"]\s*\)')


def sync_mock_data(_args=None) -> None:
    """Regenerate src/data/MockData.lua from data/characters/*.json.

    This does NOT re-encode JSON into a Lua table literal — it glues the raw
    file contents into a JSON array and wraps that verbatim text in
    JSON.decode([==[ ... ]==]). The generated file is therefore just your
    JSON, byte-for-byte, plus two lines of Lua — never a hand-authored-looking
    duplicate. TTS's Lua sandbox can't read files from disk at runtime, so
    *some* .lua wrapper has to exist for require() to find; this keeps it as
    thin as that constraint allows. Hand edits to MockData.lua get clobbered
    on the next sync, by design (CLAUDE.md rule 2: JSON is the source of
    truth, scripts only load it)."""
    characters_dir = DATA / "characters"
    files = sorted(characters_dir.glob("*.json"))
    if not files:
        print(f"No character JSON files found in {characters_dir}", file=sys.stderr)
        sys.exit(1)

    raw_parts = []
    for f in files:
        text = f.read_text(encoding="utf-8")
        json.loads(text)  # validate only — fail fast on typos, don't reformat
        raw_parts.append(text.strip())
    merged = "[\n" + ",\n".join(raw_parts) + "\n]\n"

    if "]==]" in merged:
        raise ValueError(
            "a character JSON file contains ']==]', which breaks the Lua "
            "long-string wrapper — rename/escape that content"
        )

    output = (
        "-- AUTO-GENERATED by `python3 tools/tts_bridge.py sync-mock`.\n"
        "-- Не редактировать руками — правьте data/characters/*.json и запустите\n"
        "-- sync-mock заново (или push, он делает это сам). Ниже — не Lua-копия,\n"
        "-- а сырой JSON из тех файлов, склеенный в массив 1:1.\n"
        "return JSON.decode([==[\n"
        f"{merged}"
        "]==])\n"
    )
    MOCK_DATA_PATH.write_text(output, encoding="utf-8")
    print(f"Wrote {MOCK_DATA_PATH.relative_to(ROOT)} from {len(files)} file(s): "
          f"{', '.join(f.name for f in files)}")


def resolve_module_file(name: str) -> Path:
    return SRC / (name.replace(".", "/") + ".lua")


def bundle_lua(entry_source: str) -> str:
    """Statically inline require()'d modules, mirroring what the TTS Editor
    VS Code extension does on Save and Play. TTS's Lua sandbox has no real
    package/require system, so every require() call site gets served at
    runtime by a tiny shim defined in a prelude, with each module's source
    wrapped as a lazily-invoked closure."""
    discovered = {}
    queue = list(REQUIRE_RE.findall(entry_source))
    while queue:
        name = queue.pop()
        if name in discovered:
            continue
        path = resolve_module_file(name)
        if not path.exists():
            raise FileNotFoundError(f'require("{name}") -> {path} not found')
        source = path.read_text(encoding="utf-8")
        discovered[name] = source
        queue.extend(REQUIRE_RE.findall(source))

    if not discovered:
        return entry_source

    prelude = [
        "local __tts_modules, __tts_cache = {}, {}",
        "local function require(name)",
        "  if __tts_cache[name] ~= nil then return __tts_cache[name] end",
        "  local fn = __tts_modules[name]",
        "  if fn == nil then error('module not found: ' .. tostring(name)) end",
        "  local result = fn()",
        "  __tts_cache[name] = result",
        "  return result",
        "end",
    ]
    for name, source in discovered.items():
        prelude.append(f'__tts_modules["{name}"] = function()')
        prelude.append(source)
        prelude.append("end")

    return "\n".join(prelude) + "\n\n" + entry_source

SEND_PORT = 39999
RECV_PORT = 39998
HOST = "127.0.0.1"


def send_message(payload: dict) -> None:
    with socket.create_connection((HOST, SEND_PORT), timeout=5) as s:
        s.sendall(json.dumps(payload).encode("utf-8"))


def wait_for_message(expected_id: int, timeout: float = 15.0) -> dict:
    """Start a one-shot listener on RECV_PORT and return the first message
    matching expected_id (mirrors how TTS's own external editor works: it
    opens a fresh connection per outgoing message and closes it when done)."""
    result = {}
    done = threading.Event()

    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srv.bind((HOST, RECV_PORT))
    srv.listen(5)
    srv.settimeout(timeout)

    def accept_loop():
        end_time = time.time() + timeout
        while time.time() < end_time and not done.is_set():
            try:
                srv.settimeout(max(0.1, end_time - time.time()))
                conn, _ = srv.accept()
            except socket.timeout:
                break
            chunks = []
            conn.settimeout(5)
            try:
                while True:
                    data = conn.recv(65536)
                    if not data:
                        break
                    chunks.append(data)
            except socket.timeout:
                pass
            conn.close()
            if not chunks:
                continue
            try:
                msg = json.loads(b"".join(chunks).decode("utf-8"))
            except json.JSONDecodeError:
                continue
            if msg.get("messageID") == expected_id:
                result["msg"] = msg
                done.set()
                break

    t = threading.Thread(target=accept_loop, daemon=True)
    t.start()
    t.join(timeout + 1)
    srv.close()
    if "msg" not in result:
        raise TimeoutError(
            f"Timed out waiting for messageID={expected_id} from TTS. "
            "Is Tabletop Simulator running with a save loaded?"
        )
    return result["msg"]


def safe_filename(name: str, guid: str) -> str:
    """Mirror tts-editor's naming: object name minus path-hostile chars, then guid."""
    name = re.sub(r'[":<>/\\|?*\r\n]', "", (name or "Object")).strip() or "Object"
    return f"{name}.{guid}"


def pull(_args) -> None:
    OBJECTS.mkdir(parents=True, exist_ok=True)

    print("Requesting scripts from TTS...")
    send_message({"messageID": 0})
    msg = wait_for_message(expected_id=1)
    states = msg.get("scriptStates", [])
    print(f"Received {len(states)} script state(s).")

    manifest = []
    for st in states:
        guid = st["guid"]
        name = st.get("name", "Object")
        script = st.get("script", "") or ""
        ui = st.get("ui", "") or ""

        if guid == "-1":
            lua_path = OBJECTS / "Global.lua"
            xml_path = OBJECTS / "Global.xml"
        else:
            base = safe_filename(name, guid)
            lua_path = OBJECTS / f"{base}.lua"
            xml_path = OBJECTS / f"{base}.xml"

        lua_path.write_text(script, encoding="utf-8")
        xml_path.write_text(ui, encoding="utf-8")

        manifest.append(
            {
                "guid": guid,
                "name": name,
                "lua": str(lua_path.relative_to(ROOT)),
                "xml": str(xml_path.relative_to(ROOT)),
            }
        )

    MANIFEST.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {len(manifest)} object(s) to {OBJECTS.relative_to(ROOT)}/")


def push(_args) -> None:
    if not MANIFEST.exists():
        print("No .tts/manifest.json found — run `pull` first.", file=sys.stderr)
        sys.exit(1)

    sync_mock_data()

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    script_states = []
    for entry in manifest:
        lua_path = ROOT / entry["lua"]
        xml_path = ROOT / entry["xml"]
        script = lua_path.read_text(encoding="utf-8") if lua_path.exists() else ""
        script = bundle_lua(script)
        ui = xml_path.read_text(encoding="utf-8") if xml_path.exists() else ""
        script_states.append(
            {"guid": entry["guid"], "script": script, "ui": ui}
        )

    print(f"Pushing {len(script_states)} object(s) to TTS (Save & Play)...")
    send_message({"messageID": 1, "scriptStates": script_states})
    try:
        wait_for_message(expected_id=1, timeout=20)
        print("TTS reloaded successfully.")
    except TimeoutError:
        print("Sent, but did not see a reload confirmation in time.", file=sys.stderr)
    except OSError as e:
        print(f"Sent (couldn't listen for confirmation: {e}).", file=sys.stderr)
        print("Port 39998 is likely held by the VS Code extension — check its output/console, or TTS directly, to confirm the reload.", file=sys.stderr)


def watch(_args) -> None:
    print(f"Listening on {HOST}:{RECV_PORT} for TTS console output (Ctrl+C to stop)...")
    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srv.bind((HOST, RECV_PORT))
    srv.listen(5)
    try:
        while True:
            conn, _ = srv.accept()
            chunks = []
            while True:
                data = conn.recv(65536)
                if not data:
                    break
                chunks.append(data)
            conn.close()
            if not chunks:
                continue
            try:
                msg = json.loads(b"".join(chunks).decode("utf-8"))
            except json.JSONDecodeError:
                continue
            mid = msg.get("messageID")
            if mid == 2:
                print(f"[print] {msg.get('message')}")
            elif mid == 3:
                print(f"[error] {msg.get('errorMessagePrefix', '')}{msg.get('error')}")
            elif mid == 6:
                print("[saved]")
            elif mid == 7:
                print(f"[object created] guid={msg.get('guid')}")
            elif mid == 0:
                print(f"[scripting editor opened for new object] {msg.get('scriptStates')}")
            else:
                print(f"[msg {mid}] {msg}")
    except KeyboardInterrupt:
        pass
    finally:
        srv.close()


def main():
    parser = argparse.ArgumentParser(description="TTS External Editor API bridge")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("pull", help="fetch scripts/UI from the running game into src/")
    sub.add_parser("push", help="send src/ back to the running game (Save & Play)")
    sub.add_parser("watch", help="print live print()/error messages from the game")
    sub.add_parser("sync-mock", help="regenerate src/data/MockData.lua from data/characters/*.json")

    args = parser.parse_args()
    {"pull": pull, "push": push, "watch": watch, "sync-mock": sync_mock_data}[args.command](args)


if __name__ == "__main__":
    main()
